title: Vianney's blog
author: Vianney FAIVRE
linkedin_username: vianneyfaivre
github_username: vianneyfaivre
social:
  name: Vianney FAIVRE
  links:
    - https://www.linkedin.com/in/vianneyfaivre
    - https://github.com/vianneyfaivre

permalink: /:categories/:title
paginate: 15

excerpt_separator: <!--more-->

google_analytics: UA-139044020-1

theme: minima
header_pages: 
  - tech.html
  - things.html
  - recettes.html
  - about.md

# Hide posts when post.date > today
future: false
 
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

# Adding the flag "isFlag" to flags
defaults:
  - scope:
      path: "assets/images/flags-small"
    values:
      isFlag: true
