title: Vianney FAIVRE
author: Vianney FAIVRE
linkedin_username: vianneyfaivre
github_username: vianneyfaivre
rss: RSS
social:
  name: Vianney FAIVRE
  links:
    - https://www.linkedin.com/in/vianneyfaivre
    - https://github.com/vianneyfaivre

permalink: /:categories/:title

excerpt_separator: <!--more-->

encoding: UTF-8

# Source can be found in /opt/homebrew/lib/ruby/gems/3.0.0/gems/minima-<version>
theme: minima

header_pages: 
  - things.html
  - recettes.html
  - about.html

# false = Hide posts when post.date > today
future: false
 
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-coffeescript

# Tag static resources
defaults:
  - scope:
      path: "assets/images/flags-small"
    values:
      isFlag: true
  - scope:
      path: "assets/images/cooking/recipes"
    values:
      isRecipePic: true
