title: Vianney's blog
author: Vianney FAIVRE
linkedin_username: vianneyfaivre
github_username: vianneyfaivre
rss: RSS
social:
  name: Vianney FAIVRE
  links:
    - https://www.linkedin.com/in/vianneyfaivre
    - https://github.com/vianneyfaivre

permalink: /:categories/:title
paginate: 15

excerpt_separator: <!--more-->

google_analytics: UA-139044020-1

# Source can be found in /<path_to_ruby>/gems/minima-<version>
theme: minima

header_pages: 
  - tech.html
  - things.html
  - recettes.html
  - about.html

# false = Hide posts when post.date > today
future: false
 
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Adding the flag "isFlag" to flags
defaults:
  - scope:
      path: "assets/images/flags-small"
    values:
      isFlag: true
